// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void setEnv({required String key, required String value}) =>
    RustLib.instance.api.crateApiEnvSetEnv(key: key, value: value);

String getEnv({required String key}) =>
    RustLib.instance.api.crateApiEnvGetEnv(key: key);

List<String> getPathsEnv({required String key, required String separator}) =>
    RustLib.instance.api.crateApiEnvGetPathsEnv(key: key, separator: separator);

void setOrAppendPathsEnv({
  required String key,
  required List<String> paths,
  required String separator,
}) => RustLib.instance.api.crateApiEnvSetOrAppendPathsEnv(
  key: key,
  paths: paths,
  separator: separator,
);
