// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extend_env`, `get_executable_interpreter`

void loadLibrary({required String libPath}) =>
    RustLib.instance.api.crateApiExecutorLoadLibrary(libPath: libPath);

Future<(String, String)> executeCommand({
  required String exec,
  required List<String> args,
  List<String>? ldLibraryPath,
  Map<String, String>? env,
}) => RustLib.instance.api.crateApiExecutorExecuteCommand(
  exec: exec,
  args: args,
  ldLibraryPath: ldLibraryPath,
  env: env,
);

Future<(String, String)> executePythonScript({
  required String exec,
  required String code,
  List<String>? pythonPaths,
  String? pythonLibraryDir,
}) => RustLib.instance.api.crateApiExecutorExecutePythonScript(
  exec: exec,
  code: code,
  pythonPaths: pythonPaths,
  pythonLibraryDir: pythonLibraryDir,
);
